// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBoVB7CclrwtC5koHVoK-I8lKlI_pRSlM',
    appId: '1:515738333498:web:f787aff6b6852014262003',
    messagingSenderId: '515738333498',
    projectId: 'lab-test-d20221104752',
    authDomain: 'lab-test-d20221104752.firebaseapp.com',
    storageBucket: 'lab-test-d20221104752.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4JSLXmbqi7yYdU1gjUoLYPUiGJa78AyM',
    appId: '1:515738333498:android:03405deca959b3eb262003',
    messagingSenderId: '515738333498',
    projectId: 'lab-test-d20221104752',
    storageBucket: 'lab-test-d20221104752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxFDxUXTJugt4-CKB7OegZKZ3hEcWa2qQ',
    appId: '1:515738333498:ios:74cf2c893309a3bb262003',
    messagingSenderId: '515738333498',
    projectId: 'lab-test-d20221104752',
    storageBucket: 'lab-test-d20221104752.firebasestorage.app',
    iosBundleId: 'com.example.staffData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxFDxUXTJugt4-CKB7OegZKZ3hEcWa2qQ',
    appId: '1:515738333498:ios:74cf2c893309a3bb262003',
    messagingSenderId: '515738333498',
    projectId: 'lab-test-d20221104752',
    storageBucket: 'lab-test-d20221104752.firebasestorage.app',
    iosBundleId: 'com.example.staffData',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBoVB7CclrwtC5koHVoK-I8lKlI_pRSlM',
    appId: '1:515738333498:web:2c7daffe6194c548262003',
    messagingSenderId: '515738333498',
    projectId: 'lab-test-d20221104752',
    authDomain: 'lab-test-d20221104752.firebaseapp.com',
    storageBucket: 'lab-test-d20221104752.firebasestorage.app',
  );
}
